<!--  put navigation links and everything you want at the top of each page here -->

<h3 align = "center" style = "color:green"><img src = "./img/jobtracker.png" width = "48" height = "48"> <br>JOB TRACKER 5000</h3>

<table  border = "1" width = "400" align = "center">
<tr>
<td align = "center" text-align = "center"><a href="./company.php"> <img src="./img/company.png" height = "64" width = "64"> <br>Companies</a></td>
<td align = "center" text-align = "center"><a href="./job.php"> <img src="./img/jobs.png" height = "64" width = "64"> <br>Jobs</a></td>
<td align = "center" text-align = "center"><a href="./person.php"> <img src="./img/people.png" height = "64" width = "64"> <br>People</a></td>
<td align = "center" text-align = "center"><a href="./note.php"> <img src="./img/notes.png" height = "64" width = "64"> <br>Notes</a></td>
</tr>
</table> 

<br>